### ISSUE TITLE
envy subfolder missing

### ISSUE THREAD

**Issue by HeSe** [vasmalltalk/tensorflow-vast#17]
The README refers to a .dat configuration map that is missing in this repo.
VAST-Tonel can' be loaded into Unix environments currently.
Could you please reintroduce the envy folder temporarily?

**Comment by marianopeck** [comment]
Hi Sebastian,
Yes, we moved away from ENVY to Tonel for this project. We still need to update the documentation: https://github.com/vast-community-hub/tensorflow-vast/issues/18 
But we prefer NOT to put back the ENVY .dat but instead make Tonel to work properly on Linux. We will be opening a case on that project to address that.

**Comment by marianopeck** [comment]
Here it is: https://github.com/instantiations/tonel-vast/issues/60

Does it sound good @HeSe ?

**Comment by HeSe** [comment]
Yes! Thank you! I was able to load Tonel 1.74 into my ECAP environment.
