### ISSUE TITLE
Add a simple image recognizon example

### ISSUE THREAD

**Issue by marianopeck** [vasmalltalk/tensorflow-vast#4]
I would love to have an example like this one: https://blog.insightdatascience.com/tensorflow-image-recognition-on-a-raspberry-pi-3645a1634c66

Check CgImageSupport app for our images support.

**Comment by freedomtan** [comment]
I have [a simple label_image example](https://github.com/PolyMathOrg/libtensorflow-pharo-bindings/blob/master/LibTensorFlow-Examples/LabelImage.class.st) in @SergeStinckwich's Pharo TensorFlow binding repo.

**Comment by marianopeck** [comment]
Wow. That's sooooo cool. Can't wait to having it working... Thanks for pointing it out!!

**Comment by SergeStinckwich** [comment]
I already use it for lectures. It works very well :-)

**Comment by marianopeck** [comment]
Excellent!  Were there more examples added to the pharo port that were not originally in Cuis? If so, please point them!

**Comment by marianopeck** [comment]
Hi @freedomtan 
Now that we got this working, do you know of any example of "Object Detection"? Something like [this](http://andrew.carterlunn.co.uk/programming/2018/01/24/annotating-large-datasets-with-tensorflow-object-detection-api.html) or [this](https://blog.algorithmia.com/deep-dive-into-object-detection-with-open-images-using-tensorflow/) or [this](https://www.kdnuggets.com/2018/03/google-tensorflow-object-detection-api-the-easiest-way-implement-image-recognition.html).

I wonder if we can download pre-trained models with that and then display the images from Smalltalk. Did you ever try? @SergeStinckwich ?

**Comment by freedomtan** [comment]
nope, i didn't try to do object detection  with TensorFlow C API (tried object detection, semantic segmentation, etc. in TensorFlow Lite C API before). As far as I know, for inference only, it's not hard.

1. make sure that processing ops are included in the libraries (should be yes, otherwise you have implement post-processing such as non-maximum suppression)
2. run it and collect results like what we do in label_image

**Comment by gerasdf** [comment]
I've been taking a look at
https://github.com/tensorflow/models/blob/477ed41e7e4e8a8443bc633846eb01e2182dc68a/object_detection/object_detection_tutorial.ipynb
and it's VERY possible to use any of the frozen models from
https://github.com/tensorflow/models/blob/477ed41e7e4e8a8443bc633846eb01e2182dc68a/object_detection/g3doc/detection_model_zoo.md
to get the boxes for the detected objects in images from COCO (
http://cocodataset.org/).

We don't need anything else, all is there. I will try to code what the
notebook does (In Smalltalk). I just need one full hour I estimate. I
checked already, and all we need is there... probably reading the label_map
file is the most complicated operation... but I'm sure we can figure it out

**Comment by gerasdf** [comment]
alright, the labelmap is a pbtxt, and very simple, so we can definately
load it somehow. it looks like:

item {
  name: "background"
  id: 0
  display_name: "background"
}
item {
  name: "/m/01g317"
  id: 1
  display_name: "person"
}

frim
https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_complete_label_map.pbtxt

**Comment by SergeStinckwich** [comment]
This is great ! We need some way to download datasets/serialized networks more easily.

**Comment by marianopeck** [comment]
I moved this conversation to a new issue #5  and I will close this one as we can considered it done.
